### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by DelvarWorld** [mcsoto/LogicJS#5]
If this project is published on NPM it reduces the friction of using it in other projects :)

**Comment by DelvarWorld** [comment]
Not something you're interested in?

**Comment by mcsoto** [comment]
Actually, it's alright to me. (I already published.)

________________________________
De: Andrew Ray <notifications@github.com>
Enviado: terça-feira, 16 de agosto de 2016 19:11:09
Para: mcsoto/LogicJS
Cc: mcsoto; State change
Assunto: Re: [mcsoto/LogicJS] Publish to NPM? (#5)


Not something you're interested in?

-

**Comment by DelvarWorld** [comment]
oh ok cool, wasn't sure because there's no package.json in this repo
